Repository dcSpark/cardano-multiplatform-lib, pull requests merged in 2022-08, with the labels that each got.

#99 Update crc32 type from u64 -> u32
  rust/json-gen/src/main.rs
  rust/pkg/cardano_multiplatform_lib.js.flow
  rust/src/byron/cbor.rs
  rust/src/byron/crc32.rs
  rust/src/byron/mod.rs
  rust/src/byron/serialization.rs
  rust/src/byron/utils.rs
  rust/src/error.rs
Labels: bug

#104 Fix tx id for a redeem address
  rust/src/genesis/byron/parse.rs
Labels: bug

#109 Allow using temporary exunits
  rust/pkg/cardano_multiplatform_lib.js.flow
  rust/src/builders/mod.rs
  rust/src/builders/tx_builder.rs
  rust/src/builders/utils.rs
  rust/src/builders/witness_builder.rs
  rust/src/plutus.rs
Labels: enhancement

#112 make setting redeemers a standalone build step
  rust/pkg/cardano_multiplatform_lib.js.flow
  rust/src/builders/mod.rs
  rust/src/builders/redeemer_builder.rs
  rust/src/builders/tx_builder.rs
  rust/src/builders/witness_builder.rs
Labels: enhancement

#113 Simplify tx builder metadata functions
  rust/pkg/cardano_multiplatform_lib.js.flow
  rust/src/builders/mod.rs
  rust/src/builders/tx_builder.rs
  rust/src/builders/utils.rs
  rust/src/metadata.rs
Labels: enhancement

#114 Add auxiliary data helper functions
  rust/pkg/cardano_multiplatform_lib.js.flow
  rust/src/builders/tx_builder.rs
  rust/src/builders/utils.rs
Labels: enhancement

#107 PlutusData's to/from JSON format now a string
  rust/json-gen/src/main.rs
  rust/pkg/cardano_multiplatform_lib.js.flow
  rust/src/plutus.rs
Labels: bug

#117 Add Byron txout support
  rust/json-gen/src/main.rs
  rust/pkg/cardano_multiplatform_lib.js.flow
  rust/src/byron/mod.rs
  rust/src/byron/serialization.rs
Labels: bug, enhancement

#118 Allow unchecked tx redeemer builder
  rust/Cargo.lock
  rust/json-gen/Cargo.lock
  rust/pkg/cardano_multiplatform_lib.js.flow
  rust/src/builders/tx_builder.rs
Labels: enhancement
